# 心理大模型的接口地址
emo_llm_api_path : "https://api.deepseek.com"
# 心理大模型的名称
emo_llm_name : "deepseek-chat"
# 基座大模型的接口地址
llm_api_path : "https://api.deepseek.com"
# 基座大模型的名称
llm_name : "deepseek-chat"
# embedding模型的路径
llm_api_key : "sk-b1180d98fb6648c99ac1542ea5d6d760"
embedding_model_path : "D:\\SCSE\\bge-m3"
# rerank模型的路径
rerank_model_path : "./bge-m3"
# neo4j的url
neo4j_url : "neo4j:http://10.11.37.143:7474"
# neo4j的用户名·
neo4j_username : "neo4j"
# neo4j的密码
neo4j_password : "rootroot"
# neo4j的数据库
neo4j_database : "neo4j"